### ISSUE TITLE
value of length_s

### ISSUE THREAD

**Issue by Siyuan-hub** [pbenettin/tran-SAS#1]
Hello

I would like to use SAS. Thanks for your codes!

There is one thing I cannot understand. it is the length_s. In your code, you set it as constant. it is the length of rank age. why isn't it a variable?
![image](https://user-images.githubusercontent.com/82085427/136533644-fe350ef5-f108-410c-8fb5-8fb69c20ba9b.png)
I am looking forward to your reply!

Bests,
Siyuan

**Comment by pbenettin** [comment]
Dear @Siyuan-hub, my apologies I only saw this issue today!

You are correct and `length_s` grows at any time step. The value you higlighted is the initialization and then at line 77 you'll see the command `length_s = length_s+1`.

Best,
Paolo
